name: Test Documentation
on:
  workflow_call:
    inputs:
      repoName:
        required: true
        type: string
  workflow_dispatch:
  pull_request:
    branches:
      - master
      
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.16.3]
    steps:
    - name: Obtain Source
      uses: actions/checkout@v2
    - name: Get dependencies
      env:
        cmake_version: ${{ matrix.cmake_version }}
      run: .github/workflows/scripts/get_dependencies.sh cmake doxygen sphinx
    - name: Build documentation
      env:
        cmake_version: ${{ matrix.cmake_version }}
      run: |
        set -e 
        arch="Linux-x86_64"
        cmake_command=cmake-${cmake_version}-${arch}/bin/cmake
        doc_target=${{inputs.repoName}}
        ${cmake_command} -H. -Bbuild -DBUILD_DOCS=ON -DONLY_BUILD_DOCS=ON
        ${cmake_command} --build build --target "${doc_target}"
        mkdir docs/build
        mkdir docs/build/html
        mv build/html "docs/build/html/${doc_target}"
        . venv/bin/activate
        cd docs
        make html
