name: Test Documentation
on:
  workflow_call:
    inputs:
      repoName:
        required: true
        type: string
  workflow_dispatch:
  pull_request:
    branches:
      - master
      
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake_version: [3.16.3]
    steps:
    - name: pre-build-documentation
      uses: TLW-orgtesting/ci-config/action2@v1.007
    - name: Build documentation
      env:
        cmake_version: ${{ matrix.cmake_version }}
      run: .github/workflows/scripts/build_docs.sh ${{repoName}}
